backend:
  name: github
  repo: andrew-paterson/netlify-cms-hugo-test-site
  base_url: https://9s9ttkn75e.execute-api.eu-west-1.amazonaws.com
  auth_endpoint: /prod/auth
  branch: master # Branch to update (optional; defaults to master)
site_id: www.neftlify-test.ajp-sandbox.co.za
media_folder: /static/images
public_folder: /images
collections:
  - name: "single-pages"
    label: "Single Pages"
    files:
      - label: "Home"
        name: "home"
        file: "/content/_index.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: 'Body', name: 'body', widget: 'markdown', required: false }
      - label: "About"
        name: "about"
        file: "/content/about.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: 'Body', name: 'body', widget: 'markdown', required: false }
      - label: "Contact"
        name: "contact"
        file: "/content/contact-us.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: 'Body', name: 'body', widget: 'markdown', required: false }